[package]
name = "lfj-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
ethers = "2.0"
tokio = { version = "1.15.0", features = ["full"] }
config = "0.13"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
hex = "0.4"